# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gck < Formula
  desc "Full Kubernetes environments, composed and deployed in one command"
  homepage "https://gravitee-io-labs.github.io/gck/"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.1/gck_1.2.1_darwin_amd64.zip"
      sha256 "159f30d24ec01794d5be45b6df77fdd4619c9f8aadf56daa1b187e562c2e0a1f"

      define_method(:install) do
        bin.install "gck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.1/gck_1.2.1_darwin_arm64.zip"
      sha256 "d686d43148106262c91cea82c5522e2787609238a658005fd1335a1254444f70"

      define_method(:install) do
        bin.install "gck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.1/gck_1.2.1_linux_amd64.tar.gz"
      sha256 "01b51894c600986910cc80ed142c864ed5779c8a526cc385a17b1c949cca87ef"
      define_method(:install) do
        bin.install "gck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.1/gck_1.2.1_linux_arm64.tar.gz"
      sha256 "cffe747f7d9e934849d0aebded81f8de11108dc7eba7c9119df1f24b260b877f"
      define_method(:install) do
        bin.install "gck"
      end
    end
  end

  test do
    system "#{bin}/gck", "version"
  end
end
