# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gck < Formula
  desc "Full Kubernetes environments, composed and deployed in one command"
  homepage "https://gravitee-io-labs.github.io/gck/"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.0/gck_1.2.0_darwin_amd64.zip"
      sha256 "c1080fe0d2cd7794e27a62eeb95c9d0129625b65aa77de8514871f2d1e5c820d"

      define_method(:install) do
        bin.install "gck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.0/gck_1.2.0_darwin_arm64.zip"
      sha256 "f199146ba3b7dea81b33a185cd733b47e9e5f136784a69b47bb49332fce0e4be"

      define_method(:install) do
        bin.install "gck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.0/gck_1.2.0_linux_amd64.tar.gz"
      sha256 "0b42357cac804185487fe0db5e820125d885fa2b2ce50f416389f75695020f41"
      define_method(:install) do
        bin.install "gck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gravitee-io-labs/gck/releases/download/v1.2.0/gck_1.2.0_linux_arm64.tar.gz"
      sha256 "9fe2cd847108c92546648e93465603c288f38de775e08db8bb6f3d3fafa14058"
      define_method(:install) do
        bin.install "gck"
      end
    end
  end

  test do
    system "#{bin}/gck", "version"
  end
end
