version: 2

release:
  replace_existing_artifacts: true

builds:
  - main: .
    binary: gck
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: darwin
        formats:
          - zip

brews:
  - repository:
      owner: gravitee-io-labs
      name: gck
    directory: HomebrewFormula
    homepage: https://gravitee-io-labs.github.io/gck/
    description: "Provisions ready-made stacks on local Kubernetes clusters in one command"
    license: Apache-2.0
    test: |
      system "#{bin}/gck", "version"

nfpms:
  - package_name: gck
    homepage: https://gravitee-io-labs.github.io/gck/
    description: "Provisions ready-made stacks on local Kubernetes clusters in one command"
    license: Apache-2.0
    formats:
      - deb
      - rpm

changelog:
  disable: true
