version: 2.1

orbs:
  go: circleci/go@3.0.3

jobs:
  test:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    steps:
      - checkout
      - go/install:
          version: "1.25.9"
      - run:
          name: Build gck
          command: go build -o ./gck .
      - run:
          name: Create cluster
          command: ./gck create --config gck.local.yaml --from gravitee-io/oss/apim/dbless
      - run:
          name: Verify
          command: ./gck describe gravitee
      - run:
          name: Delete cluster
          command: ./gck delete gravitee
          when: always

workflows:
  ci:
    jobs:
      - test
