name: Integration tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go build -o ./gck .

      - name: Restore mirror cache
        uses: actions/cache@v4
        with:
          path: ~/.gck/mirrors
          key: gck-mirrors-${{ hashFiles('gck.yaml') }}
          restore-keys: gck-mirrors-

      - name: Create cluster
        run: ./gck create --config gck.local.yaml --from gravitee-io/oss/apim/dbless

      - name: Verify
        run: ./gck describe gravitee

      - name: Delete cluster
        if: always()
        run: ./gck delete gravitee
